global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sop-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'demo-rest-1:8081'
        - 'audit-service-1:8082'
        - 'notification-service-1:8083'
        - 'analytics-service-1:8085'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'